### ISSUE TITLE
Error: The package named standard-app-packages does not exist

### ISSUE THREAD

**Issue by Kulikovpavel** [jordansissel/heroku-buildpack-meteor#18]
Unpacking meteor
Building meteor bundle
Errors prevented bundling:
Exception while bundling application:
Error: The package named standard-app-packages does not exist.

Get this error, when try to heroku push, 
Meteor version - 0.7.0.1-win2.

**Comment by wfleming** [comment]
Outdated: buildpack has now been updated for newer Meteors.
