### ISSUE TITLE
Readme doesn't work

### ISSUE THREAD

**Issue by mpj** [jordansissel/heroku-buildpack-meteor#2]
Following the instructions in README doesn't work. Output below:

mpj:code mattiasjim$  meteor create --example wordplay
wordplay: created.

To run your new app:
   cd wordplay
   meteor
mpj:code mattiasjim$ cd meteor
-bash: cd: meteor: No such file or directory
mpj:code mattiasjim$ cd wordplay/
mpj:wordplay mattiasjim$ git init
Initialized empty Git repository in /Users/mattiasjim/code/wordplay/.git/
mpj:wordplay mattiasjim$ git add .
mpj:wordplay mattiasjim$ git commit -m 'Sample wordplay app!'
[master (root-commit) 32dcfeb] Sample wordplay app!
 11 files changed, 174436 insertions(+), 0 deletions(-)
 create mode 100644 .meteor/.gitignore
 create mode 100644 .meteor/packages
 create mode 100644 TODO
 create mode 100644 client/wordplay.css
 create mode 100644 client/wordplay.html
 create mode 100644 client/wordplay.js
 create mode 100644 model.js
 create mode 100644 public/circle-ball-dark-antialiased.gif
 create mode 100644 server/enable2k.js
 create mode 100644 server/game.js
 create mode 100644 server/make-boggle-dict.js.noload
mpj:wordplay mattiasjim$ heroku create meteortesta --stack cedar --buildpack https://github.com/jordansissel/heroku-buildpack-meteor.git
Creating meteortesta...git push e done, stack is cedar
http://meteortesta.herokuapp.com/ | git@heroku.com:meteortesta.git
Git remote heroku added
mpj:wordplay mattiasjim$ git push heroku
heroku open
No refs in common and none specified; doing nothing.
Perhaps you should specify a branch such as 'master'.
^CKilled by signal 2.

mpj:wordplay mattiasjim$ git push heroku master
Counting objects: 17, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (16/16), done.
Writing objects: 100% (17/17), 468.50 KiB | 132 KiB/s, done.
Total 17 (delta 0), reused 0 (delta 0)

-----> Heroku receiving push
 !     Heroku push rejected, no Cedar-supported app detected

To git@heroku.com:meteortesta.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:meteortesta.git'
mpj:wordplay mattiasjim$

**Comment by wfleming** [comment]
Closing. README had gotten out of date again, has been updated to reflect recent changes in Meteor & this buildpack.
