### ISSUE TITLE
is it possible to run meteor shell?

### ISSUE THREAD

**Issue by bastiaanterhorst** [jordansissel/heroku-buildpack-meteor#20]
Hi,
It would be really useful to run the meteor shell on heroku. Is it possible? Running ```heroku run meteor shell``` does not work. Because the app is built? Is there a fix?

**Comment by wfleming** [comment]
I don't think it is possible: I haven't found any indication of there being a way to really load the shell in the production environment at all, and digging through the compiled app bundle hasn't turned up anything useful. If you find anything indicating otherwise, please let us know!
