### ISSUE TITLE
not wanted mongolab plugin

### ISSUE THREAD

**Issue by brugnara** [jordansissel/heroku-buildpack-meteor#24]
Let me start with the dessert: thank you for this buildpack and the time you spent for this amazing work. 

Now the vegetables: the create command adds mongolab plugin but in the documentation it appears to be a facultative choice. In my opinion, this is a bug.

**Comment by wfleming** [comment]
I'm inclined to agree: it was that way before I started working on this build pack, and I didn't change it simply because I was working quickly. If you put together a PR, I'd be happy to take a look.

**Comment by gdumitrescu** [comment]
@wfleming Please take a look at the #27 PR. Thanks.
