### ISSUE TITLE
Question about Procfiles

### ISSUE THREAD

**Issue by alduethadyn** [jordansissel/heroku-buildpack-meteor#30]
I'd like to be able to run some other nodejs processes on my Heroku instance, and would like to do something like:

web: node build/bundle/main.js
worker: node .job-workers/server.js

Is this possible using this buildpack?

**Comment by wfleming** [comment]
A custom `Procfile` should work fine. The trick would be how to organize the worker code in your Meteor project so that it will be available to run after compilation. Normally, all the code in your project gets bundled up into different JS files during the build phase, so a script called `.job-workers/server.js` in your repo would no longer be available to run on the dyno. But if you can get it setup so that files in your Meteor project get copied into the compiled Meteor bundle, then you can run them as workers.

You may be able to do what you're trying to do without worker dynos, though: since Node supports processes & threads better than, say, Ruby, you may be able to spin out background jobs within your web dyno. I *think* this is what you would effectively be doing if you used something like https://github.com/Differential/meteor-workers. The downside here is if your jobs need a lot of memory/CPU, it may impact your web responsiveness.

**Comment by alduethadyn** [comment]
I'm a bit of a meteor noob - is there good documentation about the build phase? I'm guessing that is the same reason the Procfile isn't being respected at the root of the project (heroku doesn't seem to see it)... It most likely isn't at the root of the built bundle.
I am thinking some of the jobs for this particular app will be longer running so hence the different worker approach. Since I am using job-collection though, I could just run the workers as a node all in a separate heroku instance.
Andy

Sent from Outlook




On Tue, Jun 9, 2015 at 11:16 AM -0700, "Will Fleming" <notifications@github.com> wrote:












A custom Procfile should work fine. The trick would be how to organize the worker code in your Meteor project so that it will be available to run after compilation. Normally, all the code in your project gets bundled up into different JS files during the build phase, so a script called .job-workers/server.js in your repo would no longer be available to run on the dyno. But if you can get it setup so that files in your Meteor project get copied into the compiled Meteor bundle, then you can run them as workers.



You may be able to do what you're trying to do without worker dynos, though: since Node supports processes & threads better than, say, Ruby, you may be able to spin out background jobs within your web dyno. I think this is what you would effectively be doing if you used something like https://github.com/Differential/meteor-workers. The downside here is if your jobs need a lot of memory/CPU, it may impact your web responsiveness.

**Comment by wfleming** [comment]
Oh, I didn't even think about the fact the `Procfile` would get moved by compilation as well. That does change things. Heroku & Meteor really aren't great friends in a lot of ways. So, I was wrong: currently the answer would be "no", unfortunately.

There's a bit of info about Meteor's build process at http://docs.meteor.com/#/full/deploying. To really get a sense for what it actually does, you're best off running `meteor build --directory some-path` on your app locally to see what it generates. To better understand the behavior of the buildpack, you can read [the source](https://github.com/jordansissel/heroku-buildpack-meteor/blob/master/bin/compile_meteor#L49-L69). Currently, the buildpack basically runs `meteor build`, then replaces the original app source with the bundled version: this may not be the best way to do things.

If you've chosen job-collection, running as a different Heroku app pointed at the same mongo DB might work. Not really sure how best to structure it, really, sorry.

**Comment by alduethadyn** [comment]
No worries - no world to me. I am still early in the process and nothing is set in stone... Do you recommend some of the other alternatives to heroku generally?
Andy

Sent from Outlook




On Tue, Jun 9, 2015 at 12:30 PM -0700, "Will Fleming" <notifications@github.com> wrote:












Oh, I didn't even think about the fact the Procfile would get moved by compilation as well. That does change things. Heroku & Meteor really aren't great friends in a lot of ways. So, I was wrong: currently the answer would be "no", unfortunately.



There's a bit of info about Meteor's build process at http://docs.meteor.com/#/full/deploying. To really get a sense for what it actually does, you're best off running meteor build --directory some-path on your app locally to see what it generates. To better understand the behavior of the buildpack, you can read the source. Currently, the buildpack basically runs meteor build, then replaces the original app source with the bundled version: this may not be the best way to do things.



If you've chosen job-collection, running as a different Heroku app pointed at the same mongo DB might work. Not really sure how best to structure it, really, sorry.

**Comment by wfleming** [comment]
I'm not hugely experienced in Meteor either, honestly, and I'm not actually using this buildpack anymore either.

We're running one app on https://modulus.io, and a lot of my friends who are more involved with Meteor seem to consider it the currently preferred host.

Good luck, @alduethadyn. I'm going to go ahead & close this issue now.

**Comment by alduethadyn** [comment]
Thanks - sorry to create an 'issue' vs a question. I'm feeling modulus may be better long run as well 

Sent from Outlook




On Tue, Jun 9, 2015 at 1:17 PM -0700, "Will Fleming" <notifications@github.com> wrote:












I'm not hugely experienced in Meteor either, honestly, and I'm not actually using this buildpack anymore either.



We're running one app on https://modulus.io, and a lot of my friends who are more involved with Meteor seem to consider it the currently preferred host.



Good luck, @alduethadyn. I'm going to go ahead & close this issue now.

**Comment by wfleming** [comment]
No worries, Andy: filing an issue was the best way to go for this kind of thing.

**Comment by joegoldbeck** [comment]
It's possible if you're willing for fork the buildpack. By changing the file in `bin/release` you can add extra lines to the procfile. Then it's a matter of knowing where in the build your worker script ends up. One option, if you want to use all of your existing Meteor goodness in that script is to use an environment variable to determine whether an instance is your standard web server or a worker process in both the procfile and your server code. For example, https://github.com/joegoldbeck/heroku-buildpack-meteor/blob/b3a9d39df0c99bcfdaf4c767071d9166272ce10e/bin/release
