### ISSUE TITLE
Installing TypeScript

### ISSUE THREAD

**Issue by dominikmayer** [jordansissel/heroku-buildpack-meteor#32]
I'm trying to get the [TypeScript compiler](https://github.com/meteor-typescript/meteor-typescript-compiler) running on Heroku. So far I'm lost because I don't know how to install typescript as a dependency.

At first I put `typescript` as a `devDependency` in a `package.json`. I tried to put that in the root as well as the `server` directory. This didn't work.

What is the proper way to add TypeScript (or any other npm module)?

**Comment by jpadvo** [comment]
I'm looking into deploying Meteor and TypeScript to Heroku, and would also love any guidance here!

**Comment by dominikmayer** [comment]
I got it working with Demeteorizer. Here's my buildpack: https://github.com/dominikmayer/demeteorizer-buildpack
